// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 1.5.1; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// z1_bus_tx //
// --------- //

#define z1_bus_tx_wrap_target 0
#define z1_bus_tx_wrap 3
#define z1_bus_tx_pio_version 0

static const uint16_t z1_bus_tx_program_instructions[] = {
            //     .wrap_target
    0x7010, //  0: out    pins, 16        side 0
    0xb042, //  1: nop                    side 0
    0xb842, //  2: nop                    side 1
    0xb042, //  3: nop                    side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program z1_bus_tx_program = {
    .instructions = z1_bus_tx_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = z1_bus_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config z1_bus_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + z1_bus_tx_wrap_target, offset + z1_bus_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

static inline void z1_bus_tx_program_init(PIO pio, uint sm, uint offset,
                                           uint clk_pin, uint data_base_pin) {
    // Configure GPIO for PIO control and set as outputs BEFORE creating config
    pio_gpio_init(pio, clk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, clk_pin, 1, true);
    for (int i = 0; i < 16; i++) {
        pio_gpio_init(pio, data_base_pin + i);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, data_base_pin, 16, true);
    // Create state machine config
    pio_sm_config c = z1_bus_tx_program_get_default_config(offset);
    // OUT pins: DATA[15:0] (16 pins)
    sm_config_set_out_pins(&c, data_base_pin, 16);
    // Side-set pin: CLK (controlled via side-set on every instruction)
    sm_config_set_sideset_pins(&c, clk_pin);
    // Autopull enabled with 16-bit threshold
    sm_config_set_out_shift(&c, false, true, 16);  // shift_right, autopull=TRUE, threshold=16
    // Clock divider for beat rate
    // beat_rate = sysclk / (div * instructions_per_beat)
    // For 5 MHz beat rate: div = 266MHz / (5MHz * 4) = 13.3
    // RC settling: 50kΩ × 100pF = 5μs time constant, 15μs for 95% settled
    sm_config_set_clkdiv(&c, 13.3f);
    // Initialize state machine with config
    pio_sm_init(pio, sm, offset, &c);
    // DO NOT enable TX at init - will be enabled per transmission (working code pattern)
    // pio_sm_set_enabled(pio, sm, true);  // REMOVED - breaks working pattern
}

#endif

