// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 1.5.1; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// z1_bus_rx //
// --------- //

#define z1_bus_rx_wrap_target 0
#define z1_bus_rx_wrap 2
#define z1_bus_rx_pio_version 0

static const uint16_t z1_bus_rx_program_instructions[] = {
            //     .wrap_target
    0x2006, //  0: wait   0 gpio, 6
    0x2386, //  1: wait   1 gpio, 6              [3]
    0x4010, //  2: in     pins, 16
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program z1_bus_rx_program = {
    .instructions = z1_bus_rx_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = z1_bus_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config z1_bus_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + z1_bus_rx_wrap_target, offset + z1_bus_rx_wrap);
    return c;
}

static inline void z1_bus_rx_program_init(PIO pio, uint sm, uint offset,
                                           uint clk_pin, uint select0_pin, uint data_base_pin) {
    pio_sm_config c = z1_bus_rx_program_get_default_config(offset);
    // IN pins: DATA[15:0] (16 pins)
    sm_config_set_in_pins(&c, data_base_pin);
    // Autopush every 16 bits (one beat)
    sm_config_set_in_shift(&c, false, true, 16);
    // Join FIFOs for deeper RX buffer (8 words)
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    // RX runs at full speed (1.0) for precise sampling
    // TX runs at 8.3125 (32 MHz), RX at 266 MHz allows fine-grained delays
    // wait instructions are not affected by clock divider (they wait for external GPIO)
    // [3] delay at 266 MHz = 11.28 ns (samples in middle of CLK=1 window)
    sm_config_set_clkdiv(&c, 1.0f);
    // CRITICAL: Configure ALL pins for PIO control
    // CLK pin MUST be under PIO control for 'wait' instructions to work!
    pio_gpio_init(pio, clk_pin);
    // DATA pins for 'in pins' instruction
    for (int i = 0; i < 16; i++) {
        pio_gpio_init(pio, data_base_pin + i);
    }
    // Set all pins as inputs (receiver never drives)
    pio_sm_set_consecutive_pindirs(pio, sm, data_base_pin, 16, false);
    // Initialize and start state machine
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

